routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('home');
Route::get('/terms-and-conditions', 'FrontendController@terms')->name('terms');
Route::get('/frequently-asked-questions', 'FrontendController@faqs')->name('faqs');
// Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/dashboard', 'BackendController@index')->name('dashboard');
Route::resource('brands', 'BrandsController');
Route::resource('categories', 'CategoriesController');
Route::resource('subcategories', 'SubcategoriesController');
Route::get('/products/search', 'ProductsController@search')->name('products.search');
Route::patch('products/{product}/change-type', 'ProductsController@changeType')->name('products.changeType');
Route::resource('products', 'ProductsController');
Route::delete('cart/empty', 'CartController@empty')->name('cart.empty');
Route::resource('cart', 'CartController');
Route::resource('orders', 'OrdersController');
Route::post('orders/add-item', 'OrdersController@addItem')->name('orders.addItem');
Route::patch('orders/update-item/{item}', 'OrdersController@updateItem')->name('orders.updateItem');
Route::delete('orders/delete-item/{item}', 'OrdersController@deleteItem')->name('orders.deleteItem');
Route::delete('orders/items/empty', 'OrdersController@empty')->name('orders.empty');
Route::post('orders/checkout', 'OrdersController@checkout')->name('orders.checkout');
Route::patch('purchase-orders/cancel/{purchaseOrder}', 'PurchaseOrdersController@cancel')->name('purchase-orders.cancel')->middleware('admin');
Route::patch('purchase-orders/receive/{purchaseOrder}', 'PurchaseOrdersController@receive')->name('purchase-orders.receive')->middleware('admin');
Route::patch('purchase-orders/complete/{purchaseOrder}', 'PurchaseOrdersController@complete')->name('purchase-orders.complete')->middleware('supplier');
Route::resource('purchase-orders', 'PurchaseOrdersController')->middleware('admin-supplier');
Route::resource('users', 'UsersController');
Route::get('/verify/{token}', 'UsersController@verify')->name('verify');
Route::resource('suppliers', 'SuppliersController');
Route::resource('terms', 'TermsController');
Route::resource('faqs', 'FaqsController');
Route::resource('slides', 'SlidesController');

/* About */
Route::get('about-us', 'AboutController@index')->name('about');
Route::get('about/edit', 'AboutController@edit')->name('about.edit');
Route::patch('about', 'AboutController@update')->name('about.update');

/* Contact */
Route::get('contact-us', 'ContactsController@index')->name('contacts');
Route::get('contact/edit', 'ContactsController@edit')->name('contacts.edit');
Route::patch('contact', 'ContactsController@update')->name('contacts.update');

/* Profile */
Route::get('user/profile', 'ProfilesController@index')->name('profile');
Route::patch('user/profile', 'ProfilesController@update')->name('profile.update');

/* Customer's Orders */
Route::get('user/orders', 'UsersController@orders')->name('user.orders');
Route::post('user/cancel-order', 'UsersController@cancelOrder')->name('user.cancelOrder');
Route::delete('user/cancel-order-item', 'UsersController@cancelOrderItem')->name('user.cancelOrderItem');

/* Inventory */
Route::get('inventory/fast-moving-items', 'InventoryController@fastMovingItems')->name('inventory.fastMovingItems');
Route::get('inventory/slow-moving-items', 'InventoryController@slowMovingItems')->name('inventory.slowMovingItems');
Route::get('inventory/critical-level', 'InventoryController@criticalLevel')->name('inventory.criticalLevel');

/* Report */
Route::get('reports', 'ReportsController@index')->name('reports.index');
Route::get('reports/inventory', 'ReportsController@inventory')->name('reports.inventory');
Route::get('reports/orders', 'ReportsController@orders')->name('reports.orders');
Route::get('reports/sales', 'ReportsController@sales')->name('reports.sales');
Route::get('reports/purchase-orders', 'ReportsController@purchaseOrders')->name('reports.purchaseOrders');

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\Faq;
use App\Term;
use App\Slide;
use App\Product;
use Illuminate\Http\Request;

class FrontendController extends Controller
{
    public function index()
    {
        $slides = Slide::latest('updated_at')->get();
        $products = Product::latest()->get();
        return view('frontend.index', compact('slides', 'products'));
    }

    public function terms()
    {
        $terms = Term::latest('updated_at')->get();
        return view('frontend.terms', compact('terms'));
    }

    public function faqs()
    {
        $faqs = Faq::latest('updated_at')->get();
        return view('frontend.faqs', compact('faqs'));
    }
}

resources/views/frontend/cart.blade.php
@extends('layouts.app')

@section('title', 'Cart')

@section('styles')
    <!-- jQuery Spinner CSS -->
    <link href="{{ asset('css/frontend/bootstrap-spinner.min.css') }}" rel="stylesheet">

    <!-- iziToast CSS -->
    <link href="{{ asset('css/iziToast.min.css') }}" rel="stylesheet">
@endsection

@section('content')
    <!--form-->
    <section id="form">
        <div class="container">
            @include('includes.message')

            <div class="row">
                <div class="col-sm-12">
                    <div class="alert alert-info">
                        <b>Note: </b> Minimum amount of <b>{{ number_format(config('env.minimum_order_amount'), 2) }}</b> to place order.
                    </div>
                </div>
                <div class="col-sm-12">
                    <table class="table table-bordered table-responsive">
                        <thead class="bg-primary" style="font-size: 1.3em;">
                            <th class="text-center">Item</th>
                            <th class="text-center">Price</th>
                            <th class="text-center">Qty</th>
                            <th class="text-center">Total</th>
                            <th></th>
                        </thead>
                        <tbody style="font-size:1.2em;">
                            @forelse (Cart::content() as $item)
                                <tr data-rowid={{ $item->rowId }} data-id="{{ $item->id }}">
                                    <td class="text-center"><strong>{{ $item->name }}</strong></td>
                                    <td class="text-center">{{ number_format($item->price, 2) }}</td>
                                    <td class="text-center">
                                        <div data-trigger="spinner" class="form-inline spinner">
                                            <button type="button" class="btn btn-default" data-spin="down">-</button>
                                            <input name="qty" type="text" class="form-control qty" value="{{ $item->qty }}" data-rule="quantity" data-max="{{ $item->model->quantity }}">
                                            <button type="button" class="btn btn-default" data-spin="up">+</button>
                                        </div>
                                    </td>
                                    <td class="text-center">
                                        <font class="itotal">
                                            {{ number_format($item->price * $item->qty, 2) }}
                                        </font>
                                    </td>
                                    <td class="text-center">
                                        <button type="button" data-id="{{ $item->rowId }}" data-name="{{ $item->name }}" class="btn btn-danger btn-circle" data-tooltip="tooltip" data-toggle="modal" data-placement="top" data-target=".deleteModal" title="delete">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="text-center alert alert-danger"><strong>*** Your Cart is Empty ***</strong></td>
                                </tr>
                            @endforelse

                            @if (Cart::content()->count())
                                <tr>
                                    <td colspan="3" class="text-right"><strong>Sub Total</strong></td>
                                    <td colspan="2" class="text-primary subtotal">{{ Cart::subtotal() }}</td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="text-right"><strong>VAT ({{ config('cart.tax') }}%)</strong></td>
                                    <td colspan="2" class="text-danger vat">{{ Cart::tax() }}</td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="text-right"><strong>Amount Due</strong></td>
                                    <td colspan="2" class="text-danger amount-due"><strong>{{ Cart::subtotal() }}</strong></td>
                                </tr>
                            @endif
                        </tbody>
                    </table>

                    <input type="hidden" class="tax" value="{{ number_format(config('cart.tax') / 100, 2) }}">
                    <input type="hidden" class="minimum-order-amount" value="{{ config('env.minimum_order_amount') }}">

                    @if (Cart::count())
                        <div class="pull-right">
                            <a class="btn btn-primary btn-lg" style="margin-top: 0" href="{{ route('categories.show', 'all') }}">Continue Shopping</a>
                            <button class="btn btn-danger btn-lg" data-toggle="modal" data-target=".emptyModal">Empty Cart</button>
                            <button class="btn btn-success btn-lg btn-check-out {{ Cart::subtotal(2, '.', '') < config('env.minimum_order_amount') ? 'hidden' : null }}" data-toggle="modal" data-target=".checkoutModal">Check Out</button>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </section>
    <!--form-->

    <!-- Remove product modal -->
    <div class="modal fade deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">Remove product from cart</h4>
                </div>
                <form class="deleteForm" action="" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        <h5>Are you sure you want to remove this product?</h5>
                        <input class="delete-rowId" type="hidden" name="rowId">

                        <div class="form-group">
                            <label>Name</label>
                            <input class="form-control delete-name" type="text" value="{{ Auth::user()->name }}" readonly>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger">REMOVE</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Remove item modal -->

    <!-- Empty card modal -->
    <div class="modal fade emptyModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{{ route('cart.empty') }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        <h4>Are you sure you want to remove all products from cart?</h4>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger">Yes</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Empty card modal -->

    <!-- Checkout modal -->
    <div class="modal fade checkoutModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">
                        <i class="fa fa-shopping-cart text-success fa-lg"></i> Check Out
                        <small class='text-primary'> Billing Information</small>
                    </h4>
                </div>
                <form action="{{ route('orders.store') }}" method="POST">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Name</label>
                            <input class="form-control" type="text" value="{{ Auth::user()->name }}" readonly>
                        </div>
                        <div class="form-group">
                            <label>Mobile No.</label>
                            <input class="form-control" type="text" value="{{ Auth::user()->profile->getFormattedMobileNo() }}" readonly>
                        </div>
                        <div class="form-group">
                            <label>Telephone No.</label>
                            <input class="form-control" type="text" value="{{ Auth::user()->profile->telephone_no ? Auth::user()->profile->getFormattedTelephoneNo() : '' }}" readonly>
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input class="form-control" type="text" value="{{ Auth::user()->email }}" readonly>
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <textarea class="form-control" readonly>{{ Auth::user()->profile->getAddress() }}</textarea>
                        </div>
                        <div class="alert alert-info">
                            Mode of Payment: <strong>Pay on Delivery</strong>
                        </div>
                        <div class="alert alert-warning">
                            *** Please wait for our call/text or email for confirmation. Thank You! ***
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Checkout modal -->
@endsection

@section('scripts')
    <!-- Spinner Plugin Js -->
    <script src="{{ asset('js/frontend/jquery.spinner.min.js') }}"></script>

    <!-- iziToast Js -->
    <script src="{{ asset('js/iziToast.min.js') }}"></script>

    <!-- Additional JS -->
    <script type="text/javascript" src="{{ asset('js/frontend/cart.js') }}"></script>
@endsection

resources/views/frontend/faqs.blade.php
@extends('layouts.app')

@section('title', 'Frequently Asked Questions')

@section('content')
    <section class="bgimage bg-imageURL-faqs">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h2>Frequently Asked Questions</h2>
                </div>
            </div>
        </div>
    </section>

    <section class="default-margin">
        <div class="container">
            <div class="row">
                <div id="id-faqs" class="col-md-12">
                    <div class="panel-group" id="accordion1" role="tablist" aria-multiselectable="true">
                        @foreach ($faqs as $key => $faq)
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="heading{{ $key }}">
                                    <h3 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#accordion{{ $key }}" href="#collapse{{ $key }}" aria-expanded="false" aria-controls="collapse{{ $key }}" class="collapsed">
                                            <span>{{ $faq->title }}</span>
                                        </a>
                                    </h3>
                                </div>

                                <div id="collapse{{ $key }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{ $key }}">
                                    <div class="panel-body">{{ $faq->description }}</div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/frontend/index.blade.php
@extends('layouts.app')

@section('title', 'Home')

@section('content')
    <section class="bg-texture">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                @foreach ($slides as $key => $slide)
                    <li data-target="#myCarousel" data-slide-to="{{ $key }}" class="{{ $key === 0 ? 'active' : null }}"></li>
                @endforeach
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                @foreach ($slides as $key => $slide)
                    <div class="item {{ $key === 0 ? 'active' : null }}">
                        <img src="{{ $slide->getImageUrl() }}" alt="image">
                        <div class="carousel-caption"></div>
                    </div>
                @endforeach
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="container">
            <div class="home-header">Latest Products</div>

            <div class="container box-products">
                <div class="row product-container">
                    @forelse ($products as $key => $product)
                        @if ($key > 11)
                            @break
                        @endif

                        <div class="col-md-3" style="margin-bottom: 30px;">
                            <div class='product-image-wrapper'>
                                <div class="main-prod">
                                    <div class="productinfo text-center">
                                        <p>
                                            <a href="{{ route('products.show', $product->slug) }}" rel="bookmark" title="{{ $product->name }}">
                                                <img src="{{ $product->getImageUrl() }}" alt="{{ $product->name }}" title="{{ $product->name }}" width="150" height="150" />
                                            </a>
                                        </p>

                                        <p>
                                            <a href="{{ route('products.show', $product->slug) }}" rel="bookmark" title="{{ $product->name }}">
                                                {{ $product->name }}
                                            </a>
                                        </p>

                                        <p>Price: {{ number_format($product->price, 2) }}</p>

                                        <a href="{{ route('products.show', $product->slug) }}" class="btn btn-default add-to-cart">
                                            <i class="fa fa-shopping-cart"></i> View Details
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @empty
                        <h2 class="text-center">No records found</h2>
                    @endforelse

                    @if (count($products) > 11)
                        <div class="col-md-12 text-center">
                            <h3><a href="{{ route('categories.show', 'all') }}">View More</a></h3>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/frontend/profile.blade.php
@extends('layouts.app')

@section('title', 'Profile')

@section('styles')
    <!-- iziToast CSS -->
    <link href="{{ asset('css/iziToast.min.css') }}" rel="stylesheet">
@endsection

@php
    $profile = Auth::user()->profile;
@endphp

@section('content')
    <section class="bg-texture">
        <div class="container" style="padding-top: 20px">
            <div class="row">
                <div class="panel panel-success">
                    <div class="panel-heading text-center"><strong style="font-size: 16px;">Update Your Profile</strong></div>
                    <div class="panel-body">
                        <div id="id-about" class="col-md-6 col-md-offset-3">
                            @include('includes.message')

                            <form action="{{ route('profile.update') }}" method="POST" class="form-profile">
                                @csrf
                                @method('PATCH')
                                <div class="form-group">
                                    <label for="email">Email address</label>
                                    <input type="email" class="form-control" placeholder="Email" value="{{ auth()->user()->email }}" readonly>
                                </div>

                                <div class="form-group">
                                    <label for="mobile_no">Mobile No.*</label>
                                    <input type="number" name="mobile_no" class="form-control" placeholder="Ex. 9123456789" value="{{ $profile->mobile_no }}">
                                </div>

                                <div class="form-group">
                                    <label for="telephone_no">Telephone No. <i>(Optional)</i></label>
                                    <input type="number" name="telephone_no" class="form-control" placeholder="Ex. 1234567" value="{{ $profile->telephone_no }}">
                                </div>

                                <div class="form-group">
                                    <label for="building_street_info">Bldg. / Street / Subd.*</label>
                                    <textarea name="building_street_info" class="form-control" rows="3" resizable="false">{{ $profile->building_street_info }}</textarea>
                                </div>

                                <div class="form-group">
                                    <label for="barangay">Barangay*</label>
                                    <input type="text" name="barangay" class="form-control" placeholder="Barangay" value="{{ $profile->barangay }}">
                                </div>

                                <div class="form-group">
                                    <label for="city">City*</label>
                                    <input type="text" name="city" class="form-control" placeholder="City" value="{{ $profile->city }}">
                                </div>

                                <div class="form-group">
                                    <label for="province">Province*</label>
                                    <input type="text" name="province" class="form-control" placeholder="Province" value="{{ $profile->province }}">
                                </div>

                                <div class="form-group">
                                    <label for="region">Region*</label>
                                    <input type="text" name="region" class="form-control" placeholder="Region" value="{{ $profile->region }}">
                                </div>

                                <div class="form-group">
                                    <label for="postal_code">Postal Code*</label>
                                    <input type="text" name="postal_code" class="form-control" placeholder="Postal Code" value="{{ $profile->postal_code }}">
                                </div>

                                <button type="submit" class="btn btn-success btn-default center-block">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    @section('scripts')
        <!-- Validation Plugin Js -->
        <script src="{{ asset('js/jquery.validate.min.js') }}"></script>

        <!-- iziToast Js -->
        <script src="{{ asset('js/iziToast.min.js') }}"></script>

        <!-- Additional JS -->
        <script type="text/javascript" src="{{ asset('js/frontend/profile.js') }}"></script>
    @endsection
@endsection

resources/views/frontend/terms.blade.php
@extends('layouts.app')

@section('title', 'Terms and Conditions')

@section('content')
    <section class="bgimage bg-imageURL-terms">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h2>Terms &amp; Conditions</h2>
                </div>
            </div>
        </div>
    </section>

    <section class="default-margin">
        <div class="container">
            <div class="row">
                <div id="id-terms" class="col-md-12">
                    <ol>
                        @foreach ($terms as $term)
                            <li>{{ $term->description }}</li>
                        @endforeach
                    </ol>
                </div>
            </div>
        </div>
    </section>
@endsection