routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('home');
Route::get('/terms-and-conditions', 'FrontendController@terms')->name('terms');
Route::get('/frequently-asked-questions', 'FrontendController@faqs')->name('faqs');
// Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/dashboard', 'BackendController@index')->name('dashboard');
Route::resource('brands', 'BrandsController');
Route::resource('categories', 'CategoriesController');
Route::resource('subcategories', 'SubcategoriesController');
Route::get('/products/search', 'ProductsController@search')->name('products.search');
Route::patch('products/{product}/change-type', 'ProductsController@changeType')->name('products.changeType');
Route::resource('products', 'ProductsController');
Route::delete('cart/empty', 'CartController@empty')->name('cart.empty');
Route::resource('cart', 'CartController');
Route::resource('orders', 'OrdersController');
Route::post('orders/add-item', 'OrdersController@addItem')->name('orders.addItem');
Route::patch('orders/update-item/{item}', 'OrdersController@updateItem')->name('orders.updateItem');
Route::delete('orders/delete-item/{item}', 'OrdersController@deleteItem')->name('orders.deleteItem');
Route::delete('orders/items/empty', 'OrdersController@empty')->name('orders.empty');
Route::post('orders/checkout', 'OrdersController@checkout')->name('orders.checkout');
Route::patch('purchase-orders/cancel/{purchaseOrder}', 'PurchaseOrdersController@cancel')->name('purchase-orders.cancel')->middleware('admin');
Route::patch('purchase-orders/receive/{purchaseOrder}', 'PurchaseOrdersController@receive')->name('purchase-orders.receive')->middleware('admin');
Route::patch('purchase-orders/complete/{purchaseOrder}', 'PurchaseOrdersController@complete')->name('purchase-orders.complete')->middleware('supplier');
Route::resource('purchase-orders', 'PurchaseOrdersController')->middleware('admin-supplier');
Route::resource('users', 'UsersController');
Route::get('/verify/{token}', 'UsersController@verify')->name('verify');
Route::resource('suppliers', 'SuppliersController');
Route::resource('terms', 'TermsController');
Route::resource('faqs', 'FaqsController');
Route::resource('slides', 'SlidesController');

/* About */
Route::get('about-us', 'AboutController@index')->name('about');
Route::get('about/edit', 'AboutController@edit')->name('about.edit');
Route::patch('about', 'AboutController@update')->name('about.update');

/* Contact */
Route::get('contact-us', 'ContactsController@index')->name('contacts');
Route::get('contact/edit', 'ContactsController@edit')->name('contacts.edit');
Route::patch('contact', 'ContactsController@update')->name('contacts.update');

/* Profile */
Route::get('user/profile', 'ProfilesController@index')->name('profile');
Route::patch('user/profile', 'ProfilesController@update')->name('profile.update');

/* Customer's Orders */
Route::get('user/orders', 'UsersController@orders')->name('user.orders');
Route::post('user/cancel-order', 'UsersController@cancelOrder')->name('user.cancelOrder');
Route::delete('user/cancel-order-item', 'UsersController@cancelOrderItem')->name('user.cancelOrderItem');

/* Inventory */
Route::get('inventory/fast-moving-items', 'InventoryController@fastMovingItems')->name('inventory.fastMovingItems');
Route::get('inventory/slow-moving-items', 'InventoryController@slowMovingItems')->name('inventory.slowMovingItems');
Route::get('inventory/critical-level', 'InventoryController@criticalLevel')->name('inventory.criticalLevel');

/* Report */
Route::get('reports', 'ReportsController@index')->name('reports.index');
Route::get('reports/inventory', 'ReportsController@inventory')->name('reports.inventory');
Route::get('reports/orders', 'ReportsController@orders')->name('reports.orders');
Route::get('reports/sales', 'ReportsController@sales')->name('reports.sales');
Route::get('reports/purchase-orders', 'ReportsController@purchaseOrders')->name('reports.purchaseOrders');

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use App\About;
use App\Order;
use App\Product;
use Illuminate\Http\Request;

class BackendController extends Controller
{
    public function __construct()
    {
        $this->middleware('staff');
    }

    public function index()
    {
        $orders = Order::all()->groupBy('status_id');
        $inventory = Product::all();
        $fastMoving = $inventory->where('order_count', '>=', config('env.fast_moving_count'));
        $slowMoving = $inventory
            ->where('order_count', '>=', 1)
            ->where('order_count', '<=', config('env.fast_moving_count') - 1);
        $criticalLevel = $inventory->where('quantity', '<=', config('env.critical_level'));

        $orderCount = [
            'pending' => $orders[1]->count(),
            'to-ship' => $orders[2]->count(),
            'to-receive' => $orders[3]->count(),
            'completed' => $orders[4]->count(),
            'cancelled' => $orders[5]->count()
        ];

        $inventoryCount = [
            'all' => $inventory->count(),
            'fast-moving' => $fastMoving->count(),
            'slow-moving' => $slowMoving->count(),
            'critical-level' => $criticalLevel->count()
        ];

        return view('backend.dashboard', compact('orderCount', 'inventoryCount'));
    }
}

resources/views/includes/backend/header.blade.php
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title') | {{ config('app.name') }}</title>
    <!-- Favicon-->
    <link rel="icon" href="{{ asset('favicon.ico') }}" type="image/x-icon">

    <!-- Material Icons -->
    <link href="{{ asset('css/backend/material-icons.css') }}" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Fontawesome Css -->
    <link href="{{ asset('css/fontawesome-all.min.css') }}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset('css/backend/waves.min.css') }}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset('css/backend/animate.min.css') }}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset('css/backend/style.min.css') }}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{ asset('css/backend/theme-blue.min.css') }}" rel="stylesheet">
    
    <!-- Additional Css -->
    @yield('styles')
</head>

resources/views/includes/backend/page-loader.blade.php
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>

resources/views/includes/backend/script.blade.php
<!-- Jquery Core Js -->
<script src="{{ asset('js/jquery.min.js') }}"></script>

<!-- Bootstrap Core Js -->
<script src="{{ asset('js/bootstrap.min.js') }}"></script>

<!-- Slimscroll Plugin Js -->
<script src="{{ asset('js/backend/jquery.slimscroll.min.js') }}"></script>

<!-- Waves Effect Plugin Js -->
<script src="{{ asset('js/backend/waves.min.js') }}"></script>

<!-- Custom Js -->
<script src="{{ asset('js/backend/admin.js') }}"></script>

<!-- Additional script -->
@yield('scripts')

resources/views/includes/backend/sidebar.blade.php
<aside id="leftsidebar" class="sidebar">
    <!-- User Info -->
    <div class="user-info">
        <div class="image">
            <img src="{{ asset('images/user.png') }}" width="48" height="48" alt="User" />
        </div>

        <div class="info-container">
            <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }}</div>
            <div class="email">{{ Auth::user()->email }}</div>
            <div class="btn-group user-helper-dropdown">
                <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:void(0);"
                        onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                            <i class="material-icons">input</i> Sign Out
                        </a>
                    </li>
                </ul>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden">
                    @csrf
                </form>
            </div>
        </div>
    </div>
    <!-- #User Info -->

    <!-- Menu -->
    <div class="menu">
        <ul class="list">
            <li class="header">MAIN NAVIGATION</li>

            @if (Auth::user()->isSupplier())
                <li class="{{ Request::is('purchase-orders*') ? 'active' : null }}">
                    <a href="{{ route('purchase-orders.index') }}">
                        <i class="material-icons">list</i>
                        <span>Purchase Orders</span>
                    </a>
                </li>
            @else
                <li class="{{ Request::is('dashboard') ? 'active' : null }}">
                    <a href="{{ route('dashboard') }}">
                        <i class="material-icons">dashboard</i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="{{ Request::is('products') || Request::is('inventory/fast-moving-items') || Request::is('inventory/slow-moving-items') || Request::is('inventory/critical-level') ? 'active' : null }}">
                    <a href="javascript:void(0)" class="menu-toggle">
                        <i class="material-icons">store</i>
                        <span>Inventory</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="{{ Request::is('products') ? 'active' : null }}">
                            <a href="{{ route('products.index') }}">Products</a>
                        </li>
                        <li class="{{ Request::is('inventory/fast-moving-items') ? 'active' : null }}">
                            <a href="{{ route('inventory.fastMovingItems') }}">Fast Moving Items</a>
                        </li>
                        <li class="{{ Request::is('inventory/slow-moving-items') ? 'active' : null }}">
                            <a href="{{ route('inventory.slowMovingItems') }}">Slow Moving Items</a>
                        </li>
                        <li class="{{ Request::is('inventory/critical-level') ? 'active' : null }}">
                            <a href="{{ route('inventory.criticalLevel') }}">Critical Level</a>
                        </li>
                    </ul>
                </li>
                <li class="{{ Request::is('orders') || Request::is('orders/create') ? 'active' : null }}">
                    <a href="javascript:void(0)" class="menu-toggle" href="{{ route('orders.index') }}">
                        <i class="material-icons">shopping_cart</i>
                        <span>Orders</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="{{ Request::is('orders') ? 'active' : null }}">
                            <a href="{{ route('orders.index') }}">View</a>
                        </li>
                        <li class="{{ Request::is('orders/create') ? 'active' : null }}">
                            <a href="{{ route('orders.create') }}">Create</a>
                        </li>
                    </ul>
                </li>
                <li class="{{ Request::is('purchase-orders*') ? 'active' : null }}">
                    <a href="{{ route('purchase-orders.index') }}">
                        <i class="material-icons">list</i>
                        <span>Purchase Orders</span>
                    </a>
                </li>
                @if (Auth::user()->isAdmin())
                    <li class="{{ Request::is('users') ? 'active' : null }}">
                        <a href="{{ route('users.index') }}">
                            <i class="material-icons">people</i>
                            <span>Users</span>
                        </a>
                    </li>

                    <li class="{{ Request::is('suppliers') ? 'active' : null }}">
                        <a href="{{ route('suppliers.index') }}">
                            <i class="material-icons">supervised_user_circle</i>
                            <span>Suppliers</span>
                        </a>
                    </li>
                @endif
                <li class="{{ Request::is('reports') ? 'active' : null }}">
                    <a href="{{ route('reports.index') }}">
                        <i class="material-icons">table_chart</i>
                        <span>Reports</span>
                    </a>
                </li>
                <li class="{{ Request::is('brands') || Request::is('categories') || Request::is('subcategories') ? 'active' : null }}">
                    <a href="javascript:void(0)" class="menu-toggle">
                        <i class="material-icons">category</i>
                        <span>Product Settings</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="{{ Request::is('brands') ? 'active' : null }}">
                            <a href="{{ route('brands.index') }}">Brands</a>
                        </li>
                        <li class="{{ Request::is('categories') ? 'active' : null }}">
                            <a href="{{ route('categories.index') }}">Categories</a>
                        </li>
                        <li class="{{ Request::is('subcategories') ? 'active' : null }}">
                            <a href="{{ route('subcategories.index') }}">Subcategories</a>
                        </li>
                    </ul>
                </li>
                <li class="{{ Request::is('slides') || Request::is('about/edit') || Request::is('contact/edit') || Request::is('faqs') || Request::is('terms')  ? 'active' : null }}">
                    <a href="javascript:void(0)" class="menu-toggle">
                        <i class="material-icons">settings</i>
                        <span>Page Settings</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="{{ Request::is('slides') ? 'active' : null }}">
                            <a href="{{ route('slides.index') }}">Slides</a>
                        </li>
                        <li class="{{ Request::is('about/edit') ? 'active' : null }}">
                            <a href="{{ route('about.edit') }}">About</a>
                        </li>
                        <li class="{{ Request::is('contact/edit') ? 'active' : null }}">
                            <a href="{{ route('contacts.edit') }}">Contact</a>
                        </li>
                        <li class="{{ Request::is('faqs') ? 'active' : null }}">
                            <a href="{{ route('faqs.index') }}">Frequently Asked Questions</a>
                        </li>
                        <li class="{{ Request::is('terms') ? 'active' : null }}">
                            <a href="{{ route('terms.index') }}">Terms and Conditions</a>
                        </li>
                    </ul>
                </li>
            @endif
        </ul>
    </div>
    <!-- #Menu -->

    <!-- Footer -->
    <div class="legal">
        <div class="copyright">
            &copy; {{ date('Y') }} <a href="javascript:void(0);">{{ config('app.name') }}</a>.
        </div>
        <div class="version">
            <b>Version: </b> 1.0.0
        </div>
    </div>
    <!-- #Footer -->
</aside>

resources/views/includes/backend/topbar.blade.php
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            {{-- <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a> --}}
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="{{ route('dashboard') }}">{{ config('app.name') }}</a>
        </div>
    </div>
</nav>