routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('home');
Route::get('/terms-and-conditions', 'FrontendController@terms')->name('terms');
Route::get('/frequently-asked-questions', 'FrontendController@faqs')->name('faqs');
// Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/dashboard', 'BackendController@index')->name('dashboard');
Route::resource('brands', 'BrandsController');
Route::resource('categories', 'CategoriesController');
Route::resource('subcategories', 'SubcategoriesController');
Route::get('/products/search', 'ProductsController@search')->name('products.search');
Route::patch('products/{product}/change-type', 'ProductsController@changeType')->name('products.changeType');
Route::resource('products', 'ProductsController');
Route::delete('cart/empty', 'CartController@empty')->name('cart.empty');
Route::resource('cart', 'CartController');
Route::resource('orders', 'OrdersController');
Route::post('orders/add-item', 'OrdersController@addItem')->name('orders.addItem');
Route::patch('orders/update-item/{item}', 'OrdersController@updateItem')->name('orders.updateItem');
Route::delete('orders/delete-item/{item}', 'OrdersController@deleteItem')->name('orders.deleteItem');
Route::delete('orders/items/empty', 'OrdersController@empty')->name('orders.empty');
Route::post('orders/checkout', 'OrdersController@checkout')->name('orders.checkout');
Route::patch('purchase-orders/cancel/{purchaseOrder}', 'PurchaseOrdersController@cancel')->name('purchase-orders.cancel')->middleware('admin');
Route::patch('purchase-orders/receive/{purchaseOrder}', 'PurchaseOrdersController@receive')->name('purchase-orders.receive')->middleware('admin');
Route::patch('purchase-orders/complete/{purchaseOrder}', 'PurchaseOrdersController@complete')->name('purchase-orders.complete')->middleware('supplier');
Route::resource('purchase-orders', 'PurchaseOrdersController')->middleware('admin-supplier');
Route::resource('users', 'UsersController');
Route::get('/verify/{token}', 'UsersController@verify')->name('verify');
Route::resource('suppliers', 'SuppliersController');
Route::resource('terms', 'TermsController');
Route::resource('faqs', 'FaqsController');
Route::resource('slides', 'SlidesController');

/* About */
Route::get('about-us', 'AboutController@index')->name('about');
Route::get('about/edit', 'AboutController@edit')->name('about.edit');
Route::patch('about', 'AboutController@update')->name('about.update');

/* Contact */
Route::get('contact-us', 'ContactsController@index')->name('contacts');
Route::get('contact/edit', 'ContactsController@edit')->name('contacts.edit');
Route::patch('contact', 'ContactsController@update')->name('contacts.update');

/* Profile */
Route::get('user/profile', 'ProfilesController@index')->name('profile');
Route::patch('user/profile', 'ProfilesController@update')->name('profile.update');

/* Customer's Orders */
Route::get('user/orders', 'UsersController@orders')->name('user.orders');
Route::post('user/cancel-order', 'UsersController@cancelOrder')->name('user.cancelOrder');
Route::delete('user/cancel-order-item', 'UsersController@cancelOrderItem')->name('user.cancelOrderItem');

/* Inventory */
Route::get('inventory/fast-moving-items', 'InventoryController@fastMovingItems')->name('inventory.fastMovingItems');
Route::get('inventory/slow-moving-items', 'InventoryController@slowMovingItems')->name('inventory.slowMovingItems');
Route::get('inventory/critical-level', 'InventoryController@criticalLevel')->name('inventory.criticalLevel');

/* Report */
Route::get('reports', 'ReportsController@index')->name('reports.index');
Route::get('reports/inventory', 'ReportsController@inventory')->name('reports.inventory');
Route::get('reports/orders', 'ReportsController@orders')->name('reports.orders');
Route::get('reports/sales', 'ReportsController@sales')->name('reports.sales');
Route::get('reports/purchase-orders', 'ReportsController@purchaseOrders')->name('reports.purchaseOrders');

app/Subcategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subcategory extends Model
{
    protected $fillable = ['category_id', 'name', 'slug','description'];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function products()
    {
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/SubcategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use App\Subcategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class SubcategoriesController extends Controller
{
    public function __construct()
    {
        $this->middleware('staff')->except('show');
    }

    public function index()
    {
        $subcategories = Subcategory::latest()->get();
        $categories = Category::all()->sortBy('name');
        return view('subcategories.index', compact('subcategories', 'categories'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'category_id' => 'required',
            'name' => 'required|unique:subcategories,name,NULL,id,category_id,'.$request->category_id
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        $subcategory = Subcategory::create([
            'category_id' => $request->category_id,
            'name' => $request->name,
            'slug' => str_slug($request->name),
            'description' => $request->description
        ]);
        $subcategory = $subcategory->load('category');

        return response()->json(['success' => 'Subcategory successfully saved', 'data' => $subcategory]);
    }

    public function update(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'category_id' => 'required',
            'name' => "required|unique:subcategories,name,$request->id,id,category_id,$request->category_id"
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        $subcategory = Subcategory::find($request->id);
        $subcategory->category_id = $request->category_id;
        $subcategory->name = $request->name;
        $subcategory->slug = str_slug($request->name);
        $subcategory->description = $request->description;
        $subcategory->save();
        $subcategory = $subcategory->load('category');

        return response()->json(['success' => 'Subcategory successfully updated', 'data' => $subcategory]);
    }

    public function destroy($id)
    {
        try {
            Subcategory::destroy($id);
            return response()->json(['success' => 'Subcategory successfully deleted']);
        } catch (Exception $e) {
            return response()->json(['error' => $e->getMessage()]);
        };
    }

    public function show($slug)
    {
        if (strcmp($slug, "all") === 0) {
            $subcategory = (object) ['name' => 'All', 'slug' => 'all'];
            $products = Product::latest('updated_at')->paginate(12);
        } else {
            $subcategory = Subcategory::where('slug', $slug)->firstOrFail();
            $products = Product::where('subcategory_id', $subcategory->id)->latest('updated_at')->paginate(12);
        }
        
        return view('subcategories.show', compact('products', 'subcategory'));
    }
}

resources/views/subcategories/index.blade.php
@extends('layouts.backend')

@section('title', 'Subcategories')

@section('styles')
    <!-- JQuery dataTables CSS -->
    <link href="{{ asset('css/backend/datatables.min.css') }}" rel="stylesheet">

    <!-- iziToast CSS -->
    <link href="{{ asset('css/iziToast.min.css') }}" rel="stylesheet">

    <!-- bootstrap-select CSS -->
    <link href="{{ asset('css/bootstrap-select.min.css') }}" rel="stylesheet">

    <!-- Additional CSS -->
    <link href="{{ asset('css/backend/common.css') }}" rel="stylesheet">
@endsection

@section('content')
    @component('components.backend.block-header')
        SUBCATEGORIES
    @endcomponent

    <div class="row clearfix">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="header">
                    <div class="row clearfix">
                        <div class="col-md-6 col-xs-6">
                            <h2>List of Subcategories</h2>
                        </div>

                        <div class="col-md-6 col-xs-6 text-right">
                            <button type="button" class="btn btn-primary waves-effect" data-toggle="modal" data-target=".addModal">
                                <i class="material-icons">add</i>
                                <span>Add new subcategory</span>
                            </button>
                        </div>
                    </div>
                </div>

                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center">Actions</th>
                                    <th>Category Id</th>
                                    <th class="text-center">Category</th>
                                    <th class="text-center">Name</th>
                                    <th class="text-center">Description</th>
                                    <th class="text-center">Created At</th>
                                    <th class="text-center">Updated At</th>
                                </tr>
                            </thead>
                            <tbody class="text-center">
                                @forelse ($subcategories as $subcategory)
                                    <tr class="row{{ $subcategory->id }}">
                                        <td class="btnActionContainer">
                                            <button type="button" data-id="{{ $subcategory->id }}" class="btn btn-success btn-circle btn-action waves-effect waves-circle waves-float" data-tooltip="tooltip" data-toggle="modal" data-placement="top" data-target=".editModal" title="edit">
                                                <i class="material-icons">edit</i>
                                            </button>
                                            &nbsp;
                                            <button type="button" data-id="{{ $subcategory->id }}" class="btn btn-danger btn-circle btn-action waves-effect waves-circle waves-float" data-tooltip="tooltip" data-toggle="modal" data-placement="top" data-target=".deleteModal" title="delete">
                                                <i class="material-icons">delete</i>
                                            </button>
                                        </td>
                                        <td class="category_id-{{ $subcategory->id }}">{{ $subcategory->category_id }}</td>
                                        <td class="category_name-{{ $subcategory->id }}">{{ $subcategory->category->name }}</td>
                                        <td class="name-{{ $subcategory->id }}">{{ $subcategory->name }}</td>
                                        <td class="description-{{ $subcategory->id }}">{{ $subcategory->description }}</td>
                                        <td data-order="{{ $subcategory->created_at }}">{{ $subcategory->created_at }}</td>
                                        <td class="updated_at-{{ $subcategory->id }}" data-order="{{ $subcategory->updated_at }}">{{ $subcategory->updated_at }}</td>
                                    </tr>
                                @empty
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade addModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">Add new subcategory</h4>
                </div>
                <form class="addForm" action="{{ route('subcategories.store') }}" method="POST">
                    <div class="modal-body">
                        <label for="category_id">Category*</label>
                        <div class="form-group">
                            <div class="form-line">
                                <select class="form-control add-category selectpicker show-tick" name="category_id">
                                    <option value="">-- Please select a category --</option>
                                    @forelse ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @empty
                                    @endforelse
                                </select>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" class="form-control add-name" name="name">
                                <label class="form-label">Name*</label>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <textarea rows="4" class="form-control no-resize add-description" name="description"></textarea>
                                <label class="form-label">Description</label>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-link btnSave waves-effect">SAVE</button>
                        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CANCEL</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade editModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">Edit subcategory</h4>
                </div>
                <form class="editForm" method="PATCH">
                    <div class="modal-body">
                        <input class="edit-id" type="hidden" name="id">

                        <label for="category_id">Category*</label>
                        <div class="form-group">
                            <div class="form-line">
                                <select class="form-control edit-category selectpicker show-tick" name="category_id">
                                    <option value="">-- Please select a category --</option>
                                    @forelse ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @empty
                                    @endforelse
                                </select>
                            </div>
                        </div>

                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" class="form-control edit-name" name="name">
                                <label class="form-label">Name*</label>
                            </div>
                        </div>

                        <div class="form-group form-float">
                            <div class="form-line">
                                <textarea rows="4" class="form-control no-resize edit-description" name="description"></textarea>
                                <label class="form-label">Description</label>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-link btnUpdate waves-effect">UPDATE</button>
                        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CANCEL</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">Delete subcategory</h4>
                </div>
                <form class="deleteForm form-horizontal" method="DELETE">
                    <div class="modal-body">
                        <h5>Are you sure you want to delete this data?</h5>
                        <input class="delete-id" type="hidden" name="id">

                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Category</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line disabled">
                                        <input type="text" class="form-control delete-category" disabled>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Name</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line disabled">
                                        <input type="text" class="form-control delete-name" disabled>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Description</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line disabled">
                                        <textarea rows="4" class="form-control no-resize delete-description" disabled></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-link btnDelete waves-effect">DELETE</button>
                        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CANCEL</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <!-- JQuery dataTables JS -->
    <script type="text/javascript" src="{{ asset('js/backend/datatables.min.js') }}"></script>

    <!-- Validation Plugin Js -->
    <script src="{{ asset('js/jquery.validate.min.js') }}"></script>

    <!-- iziToast Js -->
    <script src="{{ asset('js/iziToast.min.js') }}"></script>

    <!-- bootstrap-select Js -->
    <script src="{{ asset('js/bootstrap-select.min.js') }}"></script>

    <!-- Additional JS -->
    <script type="text/javascript" src="{{ asset('js/backend/common.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/backend/subcategories.js') }}"></script>
@endsection

resources/views/subcategories/show.blade.php
@extends('layouts.app')

@section('title', "Subcategory - $subcategory->name")

@section('content')
    <section class="bg-texture">
        <div class="container">
            <div class="home-header" style="margin-bottom: 30px;"><strong>Subcategory: </strong>{{ $subcategory->name }}</div>

            <div class="container box-products">
                <div class="row product-container">
                    @forelse ($products as $key => $product)
                        <div class="col-md-3" style="margin-bottom: 30px;">
                            <div class='product-image-wrapper'>
                                <div class="main-prod">
                                    <div class="productinfo text-center">
                                        <p>
                                            <a href="{{ route('products.show', $product->slug) }}" rel="bookmark" title="{{ $product->name }}">
                                                <img src="{{ $product->getImageUrl() }}" alt="{{ $product->name }}" title="{{ $product->name }}" width="150" height="150" />
                                            </a>
                                        </p>

                                        <p>
                                            <a href="{{ route('products.show', $product->slug) }}" rel="bookmark" title="{{ $product->name }}">
                                                {{ $product->name }}
                                            </a>
                                        </p>

                                        <p>Price: {{ number_format($product->price, 2) }}</p>

                                        <a href="{{ route('products.show', $product->slug) }}" class="btn btn-default add-to-cart">
                                            <i class="fa fa-shopping-cart"></i> View Details
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @empty
                        <h2 class="text-center">No records found</h2>
                    @endforelse

                    {{ $products->links() }}
                </div>
            </div>
        </div>
    </section>
@endsection