routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('home');
Route::get('/terms-and-conditions', 'FrontendController@terms')->name('terms');
Route::get('/frequently-asked-questions', 'FrontendController@faqs')->name('faqs');
// Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/dashboard', 'BackendController@index')->name('dashboard');
Route::resource('brands', 'BrandsController');
Route::resource('categories', 'CategoriesController');
Route::resource('subcategories', 'SubcategoriesController');
Route::get('/products/search', 'ProductsController@search')->name('products.search');
Route::patch('products/{product}/change-type', 'ProductsController@changeType')->name('products.changeType');
Route::resource('products', 'ProductsController');
Route::delete('cart/empty', 'CartController@empty')->name('cart.empty');
Route::resource('cart', 'CartController');
Route::resource('orders', 'OrdersController');
Route::post('orders/add-item', 'OrdersController@addItem')->name('orders.addItem');
Route::patch('orders/update-item/{item}', 'OrdersController@updateItem')->name('orders.updateItem');
Route::delete('orders/delete-item/{item}', 'OrdersController@deleteItem')->name('orders.deleteItem');
Route::delete('orders/items/empty', 'OrdersController@empty')->name('orders.empty');
Route::post('orders/checkout', 'OrdersController@checkout')->name('orders.checkout');
Route::patch('purchase-orders/cancel/{purchaseOrder}', 'PurchaseOrdersController@cancel')->name('purchase-orders.cancel')->middleware('admin');
Route::patch('purchase-orders/receive/{purchaseOrder}', 'PurchaseOrdersController@receive')->name('purchase-orders.receive')->middleware('admin');
Route::patch('purchase-orders/complete/{purchaseOrder}', 'PurchaseOrdersController@complete')->name('purchase-orders.complete')->middleware('supplier');
Route::resource('purchase-orders', 'PurchaseOrdersController')->middleware('admin-supplier');
Route::resource('users', 'UsersController');
Route::get('/verify/{token}', 'UsersController@verify')->name('verify');
Route::resource('suppliers', 'SuppliersController');
Route::resource('terms', 'TermsController');
Route::resource('faqs', 'FaqsController');
Route::resource('slides', 'SlidesController');

/* About */
Route::get('about-us', 'AboutController@index')->name('about');
Route::get('about/edit', 'AboutController@edit')->name('about.edit');
Route::patch('about', 'AboutController@update')->name('about.update');

/* Contact */
Route::get('contact-us', 'ContactsController@index')->name('contacts');
Route::get('contact/edit', 'ContactsController@edit')->name('contacts.edit');
Route::patch('contact', 'ContactsController@update')->name('contacts.update');

/* Profile */
Route::get('user/profile', 'ProfilesController@index')->name('profile');
Route::patch('user/profile', 'ProfilesController@update')->name('profile.update');

/* Customer's Orders */
Route::get('user/orders', 'UsersController@orders')->name('user.orders');
Route::post('user/cancel-order', 'UsersController@cancelOrder')->name('user.cancelOrder');
Route::delete('user/cancel-order-item', 'UsersController@cancelOrderItem')->name('user.cancelOrderItem');

/* Inventory */
Route::get('inventory/fast-moving-items', 'InventoryController@fastMovingItems')->name('inventory.fastMovingItems');
Route::get('inventory/slow-moving-items', 'InventoryController@slowMovingItems')->name('inventory.slowMovingItems');
Route::get('inventory/critical-level', 'InventoryController@criticalLevel')->name('inventory.criticalLevel');

/* Report */
Route::get('reports', 'ReportsController@index')->name('reports.index');
Route::get('reports/inventory', 'ReportsController@inventory')->name('reports.inventory');
Route::get('reports/orders', 'ReportsController@orders')->name('reports.orders');
Route::get('reports/sales', 'ReportsController@sales')->name('reports.sales');
Route::get('reports/purchase-orders', 'ReportsController@purchaseOrders')->name('reports.purchaseOrders');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Gloudemans\Shoppingcart\Contracts\Buyable;

class Product extends Model implements Buyable
{
    protected $fillable = ['brand_id', 'category_id', 'subcategory_id', 'supplier_id', 'name', 'slug', 'price', 'quantity', 'description', 'image'];

    public function brand()
    {
        return $this->belongsTo('App\Brand');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function subcategory()
    {
        return $this->belongsTo('App\Subcategory');
    }

    public function supplier()
    {
        return $this->belongsTo('App\User');
    }

    public function orderItem()
    {
        return $this->belongsTo('App\OrderItem');
    }

    public function getImagePath()
    {
        return public_path("images/products/$this->image");
    }

    public function getImageUrl()
    {
        return asset("images/products/$this->image");
    }

    public function scopeAvailable($query)
    {
        return $query->where('quantity', '>', 0);
    }

    public function scopeSearch($query, $searchTerm)
    {
        return $query->where('name', 'like', "%$searchTerm%");
    }

    public function isOutOfStock()
    {
        return $this->quantity == 0;
    }

    public function isCritical()
    {
        return $this->quantity <= config('env.critical_level');
    }

    public function getBuyableIdentifier($options = null)
    {
        return $this->id;
    }

    public function getBuyableDescription($options = null)
    {
        return $this->name;
    }

    public function getBuyablePrice($options = null)
    {
        return $this->price;
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Brand;
use App\Product;
use App\Category;
use App\Subcategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ProductsController extends Controller
{
    public function __construct()
    {
        $this->middleware('staff')->except(['show', 'search']);
    }

    public function index()
    {
        $brands = Brand::all()->sortBy('name');
        $categories = Category::all()->sortBy('name');
        $products = Product::latest('updated_at')->get();
        $suppliers = User::where('role', 'supplier')->get()->sortBy('name');
        return view('products.index', compact('products', 'brands', 'categories', 'suppliers'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'image' => 'required|mimes:jpeg,jpg,png',
            'name' => 'required|unique:products,name,NULL,id',
            'brand_id' => 'required',
            'subcategory_id' => 'required',
            'supplier_id' => 'required',
            'price' => 'required',
            'quantity' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        $extension = '.' . $request->image->getClientOriginalExtension();
        $imageName = sha1(time()) . $extension;
        $subcategory = Subcategory::findOrFail($request->subcategory_id);

        $product = Product::create([
            'image' => $imageName,
            'name' => $request->name,
            'slug' => str_slug($request->name),
            'brand_id' => $request->brand_id,
            'category_id' => $subcategory->category_id,
            'subcategory_id' => $request->subcategory_id,
            'supplier_id' => $request->supplier_id,
            'price' => $request->price,
            'quantity' => $request->quantity,
            'description' => $request->description
        ]);

        $request->image->move(public_path('images/products'), $imageName);
        $product->image = $product->getImageUrl();
        $product->load('brand', 'category', 'subcategory', 'supplier');

        return response()->json(['success' => 'Product successfully saved', 'data' => $product]);
    }

    public function update(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'image' => 'mimes:jpeg,jpg,png',
            'name' => "required|unique:products,name,$request->id,id",
            'brand_id' => 'required',
            'subcategory_id' => 'required',
            'supplier_id' => 'required',
            'price' => 'required',
            'quantity' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        $subcategory = Subcategory::findOrFail($request->subcategory_id);

        $product = Product::findOrFail($request->id);
        $product->name = $request->name;
        $product->slug = str_slug($request->name);
        $product->brand_id = $request->brand_id;
        $product->category_id = $subcategory->category_id;
        $product->subcategory_id = $request->subcategory_id;
        $product->supplier_id = $request->supplier_id;
        $product->price = $request->price;
        $product->quantity = $request->quantity;
        $product->description = $request->description;

        if ($request->hasFile('image')) {
            $extension = '.' . $request->image->getClientOriginalExtension();
            $imageName = sha1(time()) . $extension;
            unlink($product->getImagePath());
            $product->image = $imageName;
            $request->image->move(public_path('images/products'), $imageName);
        }

        $product->save();
        $product->load('brand', 'category', 'subcategory', 'supplier');
        $product->image = $product->getImageUrl();

        return response()->json(['success' => 'Product successfully updated', 'data' => $product]);
    }

    public function destroy($id)
    {
        try {
            $product = Product::find($id);
            unlink($product->getImagePath());
            $product->delete();
            return response()->json(['success' => 'Product successfully deleted']);
        } catch (Exception $e) {
            return response()->json(['error' => $e->getMessage()]);
        };
    }

    public function show($slug)
    {
        $product = Product::where('slug', $slug)->firstOrFail();
        return view('products.show', compact('product'));
    }

    public function search(Request $request)
    {
        $products = Product::with(['brand', 'category'])->search($request->filter);

        if ($products->count() > 0) {
            if ($request->filled('brand')) {
                $brand = $request->brand;
                $products = $products->whereHas('brand', function ($q) use ($brand) {
                    $q->where('slug', '=', $brand);
                });
            }

            if ($request->filled('category')) {
                $category = $request->category;
                $products = $products->whereHas('category', function ($q) use ($category) {
                    $q->where('slug', '=', $category);
                });
            }
        }

        $products = $products->paginate(12);

        return view('products.search', compact('products'));
    }
}

resources/views/products/search.blade.php
@extends('layouts.app')

@section('title', 'Search - ' . Request::get('filter'))

@section('content')
    <section class="bg-texture">
        <div class="container">
            <div class="home-header" style="margin-bottom: 30px;"><strong>Search results for: </strong>{{ Request::get('filter') }}</div>

            <div class="container box-products">
                <div class="row product-container">
                    @forelse ($products as $key => $product)
                        <div class="col-md-3" style="margin-bottom: 30px;">
                            <div class='product-image-wrapper'>
                                <div class="main-prod">
                                    <div class="productinfo text-center">
                                        <p>
                                            <a href="{{ route('products.show', $product->slug) }}" rel="bookmark" title="{{ $product->name }}">
                                                <img src="{{ $product->getImageUrl() }}" alt="{{ $product->name }}" title="{{ $product->name }}" width="150" height="150" />
                                            </a>
                                        </p>

                                        <p>
                                            <a href="{{ route('products.show', $product->slug) }}" rel="bookmark" title="{{ $product->name }}">
                                                {{ $product->name }}
                                            </a>
                                        </p>

                                        <p>Price: {{ number_format($product->price, 2) }}</p>

                                        <a href="{{ route('products.show', $product->slug) }}" class="btn btn-default add-to-cart">
                                            <i class="fa fa-shopping-cart"></i> View Details
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @empty
                        <h2 class="text-center">No records found</h2>
                    @endforelse

                    {{ $products->links() }}
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('title', "Product - $product->name")

@section('content')
    <section class="sw-margin">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!--product-details-->
                    <div class="product-details">
                        <div class="col-md-4">
                            <div class="view-product">
                                <img src="{{ $product->getImageUrl() }}" />
                            </div>
                        </div>
                        <div class="col-md-1"></div>
                        <div class="col-md-7">
                            <!--/product-information-->
                            <div class="product-information">
                                <h2 class="product">{{ $product->name }}</h2>

                                @if ($product->isOutOfStock())
                                    <p><b class="text-danger">Out of stock</b></p>
                                @else
                                    <br>
                                @endif

                                <p><b>Price: </b> <span class="price">{{ number_format($product->price, 2) }}</span></p>
                                <p><b>Stocks Available: </b> {{ number_format($product->quantity) }}</p>
                                <p><b>Brand: </b> <a href="{{ route('brands.show', $product->brand->slug) }}">{{ $product->brand->name }}</a></p>
                                <p><b>Category: </b> <a href="{{ route('categories.show', $product->category->slug) }}">{{ $product->category->name }}</a></p>
                                <p><b>Subcategory: </b> <a href="{{ route('subcategories.show', $product->subcategory->slug) }}">{{ $product->subcategory->name }}</a></p>
                                <p><b>Description: </b> {{ $product->description }}</p>
                                <p>@include('includes.message')</p>
                                
                                @if (!$product->isOutOfStock())
                                    <p style="margin-top: 15px;">
                                        <form method="POST" action="{{ route('cart.store') }}">
                                            @csrf
                                            <input type="hidden" name="id" value="{{ $product->id }}">
                                            <button class="btn btn-default add-to-cart" type="submit"><i class="fa fa-shopping-cart"></i>Add to Cart</button>
                                            <a class="btn btn-default" style="margin-top: 0" href="{{ route('categories.show', 'all') }}">Continue Shopping</a>
                                        </form>
                                    </p>
                                @endif
                            </div>
                            <!--/product-information-->
                        </div>
                    </div>
                    <!--/product-details-->
                </div>
            </div>
        </div>
    </section>
@endsection